### ISSUE TITLE
Word cloud words get too small to read after large number of responses

### ISSUE THREAD

**Issue by nathansherburn** [SLC3/MARS#109]
When there are many answers, it gets really small and impossible to read.

Options:
1. Have larger overlapping text
2. Remove words with lower counts after certain size (+ set min font size)
3. Allow the Word Cloud to get larger than the screen but provide the ability to pan (a la Google maps)

Solutions 1 and 3 courtesy of Carsten, Faculty of IT

**Comment by thanatos6666** [comment]
Is there a reason there's so much whitespace on the wordcloud? 
Also, it appears words are only horizontal - I recall they used to be vertical too? 
Can we revert the rendering of the words back to the original implementation?

**Comment by nathansherburn** [comment]
Yeah this is definitely an issue. The original implementation doesn't work on small screens which was an issue because lecturers wanted to be able to screen their word clouds (from their phones) for profanity before showing their classes on the projector.

I think we'll need to use either panning or overlapping text to fulfill all the requirements people are looking for. Do you have a preference?

**Comment by nathansherburn** [comment]
Another alternative is we make the word cloud a list on smaller screens and just go back to the original implementation for larger screens.

**Comment by aj1331** [comment]
Why don't we just apply a scaling factor based on the screen size. D3 is
working in pixels anyway. If it's a small screen, reduce the text size.

**Comment by nathansherburn** [comment]
Yeah this is what I have it doing at the moment. It's hard to balance the text size based on the screen height, screen width and number of words so it's just using fudge factors (based on a whole lot of trial and error) at the moment. We'll need to do the math and work it out properly though.

The other consideration is how long the words are. You can make the text huge if the words are all like "cat" ,"dog", "rabbit" but you can't if they're like "paraskavedekatriaphobia". I did do a bit of googling and found that we're pretty safe in truncating words to 24 characters though - there's very few words longer than that in almost all languages.

Perhaps we're best using the number of characters on screen and screen width alone to determine the text size?

**Comment by nathansherburn** [comment]
Fixed by https://github.com/SLC3/MARS/commit/20dc015a524c9d1be0d2952e5b06e49b3467365e
