### ISSUE TITLE
Export results throws  404 error 

### ISSUE THREAD

**Issue by nawfalCode** [SLC3/MARS#118]
To reproduce: Export Results→ Export Format (Any Format) → Export.
Error: marsService  Failed: 404 - Results not found

Also, you can export multiple choice collections while the export format indicates: word cloud all responses. 
To reproduce: Export Results→select multiple choice format all responses→ select a collection→ change the format to word cloud all responses→ export

**Comment by nathansherburn** [comment]
I ended up creating a simple fix that checks to make sure we're selected some results before sending the request to the server. See: https://github.com/SLC3/MARS/commit/bc75b7906ed4d0055128ea408ce4c61fd974daf5

This saves us setting up a $watch which we try to keep at a minimum to keep the UI snappy.
