### ISSUE TITLE
Error in editing a collection after cloning it

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#136]
Steps 
1. Go to Archive
2. Unarchive a collection
3. Clone collection (and archive the original)
4. Click "Edit Collection"
Toolbar disappears, collection dialog doesn't show, error logged below:
![image](https://cloud.githubusercontent.com/assets/4758245/19335723/1dec3744-9151-11e6-808f-fc371659ada2.png)

**Comment by nathansherburn** [comment]
collection.owners is not being populated on the cloned collection

**Comment by nathansherburn** [comment]
Refresh fixes it so it looks like it's working in the db but not on the client. Perhaps we need to request owners again on clone.
