### ISSUE TITLE
Allow plugin to re-broadcast data from lecturer side

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#140]
We require the ability for poll plugins to be able to invoke another response to the "chat room" to allow the "queuing" and "student question" plugins to be able to be updated and interacted upon on the student side.

This is required to support a student FYP that has now progressed to the point where this functionality is a bottleneck.

**Comment by aj1331** [comment]
**This is a breaking change for plugins - `resultPluginService` has been removed. Plugins should change all references of `resultPluginService` to `pollPluginService`.**

To support the broadcasting, it was necessary for `pollPluginService` to have all of the functionality of `resultPluginService`. There isn't much point having two copies of the same thing so I've removed `resultPluginService`.

**Comment by aj1331** [comment]
Forgot to explain how to use broadcasting. Use:

`pollPluginService.submitResponse(result, response, broadcast)`

Set broadcast to true and the response will be broadcast to all active users subscribed to the poll collection. It defaults to false.
