### ISSUE TITLE
Notification that a collaborator has not been successfully added to a collection

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#145]
Pollers are not able to be added to a collection until they have been logged into MARS at least once.

If someone tries to add someone that is not in the system, the user will not be added and the dialog closes. 

We need to disable the "save button" until a valid user has been selected, and provide some notification that a valid user has not been selected, with a message that says "Can't find your user? Please ask them to to log into MARS at least once".

If we get around to adding from the Monash Directory, we can drop the message.

**Comment by nathansherburn** [comment]
Would it be easier to query our database instead doing an LDAP lookup?

Then we could just have a message like: "If the person you're looking for is not showing up, ask them to become a MARS user by logging into MARS at least once."

**Comment by thanatos6666** [comment]
I believe this is what happens now (except we don't have the message).

**Comment by nathansherburn** [comment]
Ah yep - we are. Just got thrown by
> If someone tries to add someone that is not in the system, the user will not be added and the dialog closes.

It sounds like we just need a message to let people know why their colleagues aren't showing up.

**Comment by nathansherburn** [comment]
Fixed by 9685b7cb51c66c319aa703c3be69ae20c5e70118
