### ISSUE TITLE
[HIGH PRIORITY] Text display in Multichoice Poll

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#16]
Can we do this? Happy to make the bars thinner (less height)

![image](https://cloud.githubusercontent.com/assets/4758245/13164114/ed9dfeec-d706-11e5-8ffc-9b44b48decea.png)

**Comment by aj1331** [comment]
The bar chart isn't rendering properly. It needs to be reverted.
![Uploading Issue 16 - 1.PNG…]()

**Comment by aj1331** [comment]
Fixed - it now renders like this:
![issue 16 - 2](https://cloud.githubusercontent.com/assets/1275580/13432672/c6a4bb94-e022-11e5-8ef1-3fab50f74cd4.PNG)
