### ISSUE TITLE
Icon for "copy to clipboard" on edit-polls view is confusing.

### ISSUE THREAD

**Issue by aj1331** [SLC3/MARS#176]
The icon used is for "paste" but the functionality is "copy to clipboard". I think we should change it back to the copy icon.

**Comment by nathansherburn** [comment]
Yeah I'm not sure what to do here. People have complained that the copy icon is not intuitive for what it does. I tend to agree that it does appear to be a "duplicate" or "clone" icon rather than a "copy" icon.

Any other suggestions?

**Comment by thanatos6666** [comment]
https://material.io/icons/#ic_content_paste ?

**Comment by nathansherburn** [comment]
I'll make a custom icon for this

**Comment by nathansherburn** [comment]
<svg style="width:24px; height:24px;" viewBox="0 0 24 24">
      <path style="fill: #999;"
            d="M 13.830078 1.59375 A 3 3 0 0 0 10.830078 4.59375 L 6.8300781 4.59375 A 2 2 0 0 0 4.8300781 6.59375 L 4.8300781 14.292969 C 3.4144067 15.59689 2.644869 17.37331 2.2890625 19.152344 C 2.9945023 18.164728 3.8364227 17.433985 4.8300781 16.919922 L 4.8300781 19.59375 A 2 2 0 0 0 6.8300781 21.59375 L 20.830078 21.59375 A 2 2 0 0 0 22.830078 19.59375 L 22.830078 6.59375 A 2 2 0 0 0 20.830078 4.59375 L 16.830078 4.59375 A 3 3 0 0 0 13.830078 1.59375 z M 13.830078 3.59375 A 1 1 0 0 1 14.830078 4.59375 A 1 1 0 0 1 13.830078 5.59375 A 1 1 0 0 1 12.830078 4.59375 A 1 1 0 0 1 13.830078 3.59375 z M 6.8300781 6.59375 L 8.8300781 6.59375 L 8.8300781 8.59375 L 18.830078 8.59375 L 18.830078 6.59375 L 20.830078 6.59375 L 20.830078 19.59375 L 6.8300781 19.59375 L 6.8300781 16.222656 C 7.5156903 16.083979 8.2555385 16.011719 9.0625 16.011719 L 9.0625 18.537109 L 13.373047 14.226562 L 9.0625 9.9160156 L 9.0625 12.378906 C 8.2287705 12.49801 7.4884327 12.710525 6.8300781 12.996094 L 6.8300781 6.59375 z "/>
    </svg>

**Comment by nathansherburn** [comment]
Fixed in https://github.com/SLC3/MARS/commit/f1284842bb2325e9a0fbc0579343a9eef37d399d
