### ISSUE TITLE
Closing poll goes back to empty view

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#190]
When a poll is opened via the collection view, and then closed, we are returned to a blank screen.

This does not occur if we open a poll via the Upcoming Polls view.

**Comment by nathansherburn** [comment]
Fixed :)

**Comment by nathansherburn** [comment]
Nope. Maybe not.

**Comment by nathansherburn** [comment]
I was a bit overconfident there.

It's up now :)
