### ISSUE TITLE
Visual bug with icon rendering when reordering polls

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#191]
Create 2 polls in a group.
Reorder the polls to mvoe the second one up, by clicking on the "up arrow" icon.
The greyed "up arrow" on the first poll momentarily turns into a black circle

Occurs on Chrome Windows Desktop and Chrome Android Mobile.

**Comment by nathansherburn** [comment]
Seems to be a rendering issue on Chrome only - I've disabled the ink-ripple on these buttons for now.
