### ISSUE TITLE
MCQ exporter showing wrong numbers in "Total Correct" column

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#195]
"Total correct" column is showing wrong numbers on one set of results I exported (ENG1002 S2 2016 Marking View)

**Comment by nawfalCode** [comment]
I have fixed an issue with "Total Correct" when multiple choice poll has multiple answers.

**Comment by nathansherburn** [comment]
Fixed https://github.com/SLC3/MARS/commit/72875aefec25f13d8f448a93c40afb46e04be865
