### ISSUE TITLE
d3's behavior.zoom() method locks scrolling on Chrome for Android

### ISSUE THREAD

**Issue by nathansherburn** [SLC3/MARS#197]
All other browsers including IE 11 and Edge work

**Comment by thanatos6666** [comment]
Tapping on the navigation bar and scrolling re-enables scrolling again.

**Comment by nathansherburn** [comment]
Nawfal has found that this is a bug in Chrome for Android v55.x only. We have been unable to reproduce the issue on v56+. Hopefully the update will have rolled out to everyone by the time they start using MARS!
