### ISSUE TITLE
User search field

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#21]
User search in adding people to collection should match first parts "firstname". Right now, it's a bit strange. See example below:

e.g. searching for "Nathan Sherburn".

Typing "nathan" gives:

![image](https://cloud.githubusercontent.com/assets/4758245/13206052/8cc0d716-d94a-11e5-883c-1c53eddadd89.png)

Typing "sherb" gives:

![image](https://cloud.githubusercontent.com/assets/4758245/13206058/b1e3463c-d94a-11e5-82d5-7e5f696bc5ae.png)

**Comment by nathansherburn** [comment]
Added a weighting system, improved highlighting and fixed teh db search to include first and last name.
