### ISSUE TITLE
[SUPER HIGH PRIORITY] Login issues on MARS

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#22]
After a while, MARS stops allowing logins.

Testing so far:

- Server restarted
- Logged in as "jonli" from home
- Logged out and back in as "jonli", all ok.
- Closed window, went to office (20 minutes passed?).
- Login from office PC as "jonli". Browser is already logged into Monash. **Takes abnormally long time (1 min?)**, but manages to login. 
- Attempt login from Incognito browser as student "jli155". **Times out**, says "502 Bad Gateway" from "nginx/1.9.5"

![image](https://cloud.githubusercontent.com/assets/4758245/13206408/5dd7ef46-d951-11e5-93e0-73bf9f3f4177.png)
- Closed "jonli" window, open new tab and try to navigate to MARS, **Takes abnormally long time (1 min?)**, but manages to login again. 
- Purged browser cache and cookies, attempt to login as "jonli". **Unable to login, browser stays "loading" forever**.

**Comment by aj1331** [comment]
Reverted back to the previous working authentication/login code.
