### ISSUE TITLE
[LOW PRIORITY] Firefox on Mac poll creation

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#23]
Apparently, on Firefox on Mac, options B, C, D etc don't pop up on the create Multi-Choice Poll.

Needs further investigation on a Mac.

**Comment by aj1331** [comment]
I don't have access to a Mac to test this.

**Comment by thanatos6666** [comment]
I'll test this one out on someone's Mac and get back to you.

**Comment by aj1331** [comment]
Thanks - can you send me the console output from the page, and any
javascript errors that occur?

**Comment by thanatos6666** [comment]
I tried Firefox on a Macbook today, worked fine. Unsure if this was a user error. Closing this for now.
