### ISSUE TITLE
Collection view "3 dots menu" disappears.

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#24]
When clicking on a collection in the navigation menu, the **three dots menu for the collection** only appears the FIRST time you click on the collection.

If you click on a different collection, the dots do not appear, as shown below. Only after you click on "Upcoming Polls", and then BACK to a collection, do the dots reappear.

![image](https://cloud.githubusercontent.com/assets/4758245/13276894/fa1dc750-db17-11e5-9414-131f1c05aba9.png)

**Comment by aj1331** [comment]
I can't recreate this. Can you send me the steps you went through for them to disappear?

**Comment by thanatos6666** [comment]
You need at least 2 collections for this to happen. I've created another one on the Miloshi account on the server. Click between the two collections and see if it happens for you.

**Comment by aj1331** [comment]
I see what you mean now - but it doesn't happen on my local copy. I'll look
into it more.
