### ISSUE TITLE
Lecturer view of MultiChoice Poll missing X in portrait mode on Mobile (Nexus 6P)

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#26]
![screenshot_20160225-170557](https://cloud.githubusercontent.com/assets/4758245/13311376/3e908042-dbe2-11e5-9e72-9e2b3da1e7b2.png)

![screenshot_20160225-170601](https://cloud.githubusercontent.com/assets/4758245/13311378/403dd1c4-dbe2-11e5-88b3-9d6c63b310ef.png)

**Comment by aj1331** [comment]
I've changed the style of the buttons a bit so they are now proper icon buttons, consistent with my-polls. The screenshot is from Chome for a Nexus 6:

![issue 26 - 1](https://cloud.githubusercontent.com/assets/1275580/13432883/91dc4f34-e023-11e5-82a9-9d0dcb03768a.png)
