### ISSUE TITLE
Results bars not displaying in IE11

### ISSUE THREAD

**Issue by nathansherburn** [SLC3/MARS#28]

**Comment by aj1331** [comment]
This is the same issue but no solution:
https://stackoverflow.com/questions/32401278/svg-rect-not-displaying-color-on-initial-load-only-after-zoom-in-or-out-ie

**Comment by akdor1154** [comment]
To fix IE11, it sufficient to add a direct width= attribute to the SVG element. There is still an issue on resize in IE but I think that is separate. I was also seeing the same bug in Edge, was Edge working for you?
I'll do some more reading on svg attributes and submit a PR soon.

**Comment by akdor1154** [comment]
urgh, I take it back, no it isn't. It's weird, fiddling with it in IE's dev tools is usually enough to force it to display correctly, but making the resulting changes to the original source still yield the missing rect.

**Comment by nathansherburn** [comment]
<3 IE
