### ISSUE TITLE
Need better visible feedback when they log in (other than just “no current polls”)

### ISSUE THREAD

**Issue by aj1331** [SLC3/MARS#33]
From Michael's feedback. Not sure what additional visible feedback he'd like though.

**Comment by nathansherburn** [comment]
Perhaps a spinner or something? I'll ask next time we speak.

**Comment by nathansherburn** [comment]
I believe this was with respect to joining new 'feeds'.

We now have a toast:

"Subscribed! Please wait for the presenter to start a poll."
