### ISSUE TITLE
Students should be able to see a list of the streams they have joined (somewhere… from a menu)

### ISSUE THREAD

**Issue by aj1331** [SLC3/MARS#34]
From Michael's feedback.

**Comment by aj1331** [comment]
I did make a form but I don't think it's been committed. I'll get it up tonight. It's available from the user menu where the "Sign Out" item is.

**Comment by thanatos6666** [comment]
Students should also be able to unsubscribe from feeds from this list, with a confirmation dialog "Are you sure you want to unsubscribe from this feed?"
