### ISSUE TITLE
Lock and unlock icons are not particularly obvious. Could you have a Play/ pause button, and reset button.

### ISSUE THREAD

**Issue by aj1331** [SLC3/MARS#35]
From Michael's feedback.

**Comment by aj1331** [comment]
I think it depends on the terminology used for polls. Originally we had "activate"/"deactivate", then "lock"/"unlock". The icons and terminology are easy to change, and we could go to "start"/"stop", "play"/"pause" or something along those lines. 

What's everyone's preference?

**Comment by thanatos6666** [comment]
Let's go with a Play/Pause button, seems more intuitive and it's universal

**Comment by nathansherburn** [comment]
My preference is play/pause.

**Comment by nathansherburn** [comment]
Sorry didn't see your message Jon. I'm happy with play/stop too.

I was thinking play/**pause** because the poll doesn't start from the beginning after you **stop** (ie like a CD player).

I'm okay either way though. I think some form of music player style icons would work well.

**Comment by nathansherburn** [comment]
I was also thinking about making the play button a [Floating Action Button](https://www.google.com/design/spec/components/buttons-floating-action-button.html) since it's the primary action on the page.

**Comment by aj1331** [comment]
I originally had it as a FAB, but I don't think it works very well. On
larger screens it sits away from the content in the bottom right corner.
All of the other interactions are in the top right corner - I think it's a
bit awkward, and looks awkward. On smaller screens it floats over the
result view and blocks content (on the multiple choice result view it
floats over the bar for choice D).

FABs work better sitting on edges (seams and steps) or over content that
you can scroll. Mars isn't really designed around seams and steps, which is
why I don't think FABs work very well with the current interface.

**Comment by thanatos6666** [comment]
Good point, Play/Pause it is!

**Comment by nathansherburn** [comment]
Agreed - interactions in one place sounds like a better option.

**Comment by nathansherburn** [comment]
This is finished.

Note: I only modified the [icons and labels in the result view](https://github.com/SLC3/MARS/commit/24cdf2cc3dd73205dce462983dc49d2c3a91f2a1) I couldn't see any other usage of "lock/unlock" in the app.
