### ISSUE TITLE
Lock/unlock icon wrong for current poll state

### ISSUE THREAD

**Issue by aj1331** [SLC3/MARS#37]
At some point I’m pretty certain the top bar was showing the lock icon while it was locked and the unlock icon while it was locked. Later it worked fine. From Michael's feedback.

**Comment by nathansherburn** [comment]
I think we can close this now right?

**Comment by aj1331** [comment]
I don't think any of us have been able to recreate it. It's possible Michael was mixed up based on the icons. It wasn't very clear whether the lock indicated the current status of the poll, or the action to unlock the poll.

**Comment by nathansherburn** [comment]
Yeah I got confused by this too. The play/pause should take care of any future confusion though.

Side note: I got confused turning on the sync button too - if others report the same we might be better off swapping the icons for each state.
