### ISSUE TITLE
Stream code to join the collection should be displayed when managing the collection

### ISSUE THREAD

**Issue by aj1331** [SLC3/MARS#38]
i.e. when adding groups (without having to open a poll and run it to find out). I needed to create, open and run several polls to convince myself that the code was per unit rather than per poll (since it was displayed in the admin interface for the poll). From Michael's feedback.

**Comment by thanatos6666** [comment]
Moving this up higher priority now second semester is looming.

**Comment by nathansherburn** [comment]
Fixed by commit https://github.com/SLC3/MARS/commit/e199cb618d20ae7982ab8e73fa6f963485ca7d91
