### ISSUE TITLE
Multiple lecturers using one poll

### ISSUE THREAD

**Issue by nathansherburn** [SLC3/MARS#42]
At the moment, multiple lecturers can use questions from the same collection simultaneously.

However, when two lecturers try to open the *same* poll, only the first lecturer sees the results.

We are thinking the best solution is to show a message to the second lecturer: "the poll is in use".

**Note:** There is a problem here when the first lecturer accidentally leaves a poll open. We were thinking perhaps making it possible to let the second lecturer force close the other lecturer's poll.

**Comment by thanatos6666** [comment]
As discussed, since it's an easy win, I've put this as medium priority.

**Comment by aj1331** [comment]
Making the last result (regardless of user) open instead of the user's last result is an easy win. Adding notifications that the poll is in use etc. is more complex. They should be a separate issue.

**Comment by nathansherburn** [comment]
I think we're planning to just go with the first part (ie no notifications, just allow a lecturer to join another lecturer's active poll).

**Comment by nathansherburn** [comment]
... disregard that. We will still need a notification, as you said, in the poll somewhere showing multiple users are running the poll (like in google docs).

**Comment by thanatos6666** [comment]
Notifications can come later, make that a separate low priority issue. This issue should just be the easy win.
