### ISSUE TITLE
Poll button functionality

### ISSUE THREAD

**Issue by nathansherburn** [SLC3/MARS#43]
**Jon to confirm accuracy of the following**

**Current workflow:**
1. open poll
2. unlock poll
3. get responses
4. lock poll (talk about results with students)
5. close poll
... back to office ...
6. open poll (previous poll is automatically displayed)
7. reset poll
8. unlock/lock (this saves the empty poll for next use)
9. close poll

**Proposed workflow:**
1. open poll
2. unlock poll
3. get responses
4. lock poll (talk about results with students)
5. close poll
... back to office ...
6. open poll (previous poll is automatically displayed)
**7. save and reset poll** (note: this all happens with the new save icon)
8. close poll

**Required button assignment:**
Disk icon => save and reset the poll
Refresh icon => reset the poll
Lock icon => lock/unlock (no saving of results on either)

**Comment by nathansherburn** [comment]
Another thought, "Do you want to save?" dialogue box when refreshing the poll.

Pros: This will save us adding an extra button.
Cons: ???

**Comment by thanatos6666** [comment]
Good point, let's go with the "Do you want to save these results?" dialog and then we don't need an extra button.

So now we will have Play/Stop button, Reset/Save Icon, Load Past Result Icon, Exit Icon

**Comment by aj1331** [comment]
Cons: 
* Dialogs can get annoying

So the dialog should appear when the user clicks exit if new responses have been received? What should happen when the user closes the tab or browser? When they open the result next time should it open a dialog along the lines of "This result has not been saved, would you like to save it?" or leave it till they click the exit button in MARS.

Another thought - the dialog could be a prompt. That way the user can enter a name/label for the result which can be shown in the past results drop down.

**Comment by thanatos6666** [comment]
The dialog should appear when the user clicks **"Reset/Save"**, not "Exit".

If the user closes the tab or browser, and comes back to the page, act as if they never clicked "Reset/Save"

**I like the dialog as a prompt to label the result, let's go with that**, but can we make it so they don't HAVE to label it - for example, they don't want to spend time typing something in there while in front of the class, if they forgot to reset the poll before class.

**Comment by aj1331** [comment]
Yeah definitely - if it's blank it'll show up as it does now with the
timestamp and number of responses.
