### ISSUE TITLE
Mirroring across devices

### ISSUE THREAD

**Issue by nathansherburn** [SLC3/MARS#44]
Synchronise opening and closing of polls across devices.

**Comment by thanatos6666** [comment]
Moving this up the priority chain, especially as I understand it's a quick win?

**Comment by aj1331** [comment]
The mirroring is now working. Users who can access myPolls can sync their view between multiple sessions. There's a button on the toolbar in myPolls to enable/disable the syncing. It's enabled by default and remembered using localStorage.

2dc9290b668f4a4089e0471b09984cb45aa3c248

**Comment by nathansherburn** [comment]
So cool!
