### ISSUE TITLE
Discussion: Renaming "Collections" -> "Feed" 

### ISSUE THREAD

**Issue by nathansherburn** [SLC3/MARS#54]
It may help people to understand:
1) how the feed code relates to the collection
2) how to structure their polls/groups/units etc

Another idea, call the "collection" and the "feed" a "stream"

Thoughts?

**Comment by thanatos6666** [comment]
I like collection now that it's already being used.

**Comment by nathansherburn** [comment]
So maybe we change the text from "Join Feed" to "Join Collection"

**Comment by thanatos6666** [comment]
That would be logical for the lecturers, but students don't know what
"collections" are :)

**Comment by nathansherburn** [comment]
Good point. Let's keep it how it is.
