### ISSUE TITLE
Delineation between questions in a group

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#56]
Currently, the delineation between questions in a group can be slightly hard to see. Can we make this more clear? This screenshot doesn't make it clear as one of the items is being selected. Otherwise, they are all white.

Maybe a marker at the front of each question, alternating line colours, or even a line between each question?

![image](https://cloud.githubusercontent.com/assets/4758245/14419036/3f6ac0ca-0006-11e6-83f2-d6976ca53d73.png)

**Comment by nathansherburn** [comment]
Should we perhaps cut this at one line too?

Example:

![1vs2](https://cloud.githubusercontent.com/assets/3915868/14453146/53d2604c-00d6-11e6-9749-0c3c7e563d62.png)

**Comment by thanatos6666** [comment]
Ellipses would be good too

IN ADDITION, could we have a Dot, or Arrow symbol at the start of each question?
