### ISSUE TITLE
Change view synchronization icon

### ISSUE THREAD

**Issue by aj1331** [SLC3/MARS#58]
At the moment the icon matches the intended action of the button:
![issue 58 - disabled](https://cloud.githubusercontent.com/assets/1275580/14451964/7ff3a17a-00ce-11e6-86a0-1debc4c96894.png) To disable, currently enabled
![issue 58 - enabled](https://cloud.githubusercontent.com/assets/1275580/14451963/7ff3067a-00ce-11e6-8ee7-17bd2a6a9225.png) To enable, currently disabled

Is it less confusing the other way around with the icon matching the current status? If we are going to change it I'd like to do it soon before people get used to it.

**Comment by nathansherburn** [comment]
+1 for REVERSING the icons

**Comment by thanatos6666** [comment]
I think it's more intuitive to reverse the icons (tool tip can say "screen
mirroring ON" and "screen mirroring OFF"
