### ISSUE TITLE
Some android devices reported to not render the + icon in student mode

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#59]
High priority as some students couldn't join a feed in class. Workaround was to get them to subscribe from another device that was working (desktop browser).

Reported not working:

Galaxy S4

Additionally, on HTC Desire, the + was there, but the "options" menu was missing in student view. This was really old, not Chrome and Android 4.4.2.

**Comment by nathansherburn** [comment]
I have to run now but I think I've found a solution - changing the icons from ligatures to codepoints as per [this](https://github.com/google/material-design-icons/issues/230).

**Comment by aj1331** [comment]
If that's the case none of the icons would show up in myPolls too. It would be good to do some more testing on this but as a quick fix I'll add a gulp task to swap out the ligatures with numeric codes.

**Comment by nathansherburn** [comment]
Okay thanks. I just got back - anything I can do on this?

**Comment by nathansherburn** [comment]
Confirmed no icons at all on S6 default browser.
![hpkfijgi](https://cloud.githubusercontent.com/assets/3915868/14459846/b9701b48-00fd-11e6-8fb2-c2547d6966b3.jpeg)
![pojqaf90](https://cloud.githubusercontent.com/assets/3915868/14459847/b9912478-00fd-11e6-91fa-7aeacc66f4b8.jpeg)
Correction on earlier email - Note 3 default does work for some reason.
