### ISSUE TITLE
Leaderboard name display incorrect

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#69]
Currently the leaderboard displays peoples' names. It should by default display "Anonymous" if the user has not set their Nickname, then their Nickname.

There should be a button next to each username (in the red box position), such as the "eye" icon, that reveals that user's real name upon clicking, to discourage abuse, and to enable Lecturers to reveal the winner.

![image](https://cloud.githubusercontent.com/assets/4758245/15277490/6859c7a2-1b49-11e6-8fb6-4aa8399fe3bc.png)

**Comment by thanatos6666** [comment]
Sorry, should have been a separate issue, but can we get the"reveal" button next to student names?

**Comment by aj1331** [comment]
Moved to #71
