### ISSUE TITLE
Text display in Multi-choice poll lecturer view

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#7]
In the lecturer view of a multi-choice poll, the responses should include:

(i)  the question text
(ii) the number of responses for each possible choice in format (X/Y) where X is number of responses for that choice, and Y is total number of responses.

![image](https://cloud.githubusercontent.com/assets/4758245/12966336/619fcdc2-d0b1-11e5-81ff-81dbee98dafb.png)

**Comment by aj1331** [comment]
Adding the question text looked awkward, so for now I've only added the {X/Y} label.

**Comment by thanatos6666** [comment]
We'll need to have a think about how the text could be displayed. Perhaps multi-lined output, e.g:

A. <Answer Text> (X/Y)
==================== <--- bar
B. <Answer Text> (X/Y)
==================== <--- bar
C. <Answer Text> (X/Y)
==================== <--- bar
D. <Answer Text> (X/Y)
==================== <--- bar
