### ISSUE TITLE
Leaderboard names not showing Anonymous by default for some users?

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#74]
Unsure whether some users have just used their Full Name as their Display Name, or whether this is an error where some users' Display Names are not showing as Anonymous. Images below.

![image](https://cloud.githubusercontent.com/assets/4758245/15457782/65a5701c-20d3-11e6-9b46-2c4a52a27f88.png)

![image](https://cloud.githubusercontent.com/assets/4758245/15457785/72bdc25e-20d3-11e6-83ca-8991cd75cdc8.png)

**Comment by nathansherburn** [comment]
Haha we may need to look at "null Zun Wai" too. I have a feeling his
parents didn't choose 'null' as a first name :p

**Comment by thanatos6666** [comment]
Not working, now leaderboard ONLY shows Anonymous!

**Comment by thanatos6666** [comment]
All good now.
