### ISSUE TITLE
Collapse Polls in Groups view

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#75]
Poll creation is a bit unfriendly at the moment. Can we add a "Collapse Poll" button which hides the content, so we can easily navigate between polls within a group?

![image](https://cloud.githubusercontent.com/assets/4758245/15461425/2d0dc710-20fe-11e6-9efa-6b9efcd93e4e.png)

**Comment by nathansherburn** [comment]
Fixed by 84e7e038a06156ec1d4d2edc1c006ac6b161b84d
