### ISSUE TITLE
Recommend users access MARS using Chrome, FF,  Safari or Edge

### ISSUE THREAD

**Issue by nathansherburn** [SLC3/MARS#89]
Some users are finding the [IE](https://github.com/SLC3/MARS/issues/28) bug and getting stuck.

**Comment by aj1331** [comment]
What IE bug?

**Comment by nathansherburn** [comment]
https://github.com/SLC3/MARS/issues/28

**Comment by nathansherburn** [comment]
IE bugs are fixed for now
