### ISSUE TITLE
[LOW PRIORITY] Feedback, suggestions and bug link for staff

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#9]
Add a link to the following URL:

https://docs.google.com/a/monash.edu/forms/d/1Qg91GKcnJxiflAIHqekrHzyBRGmmHwktGRw1mYYFvWQ/viewform

(i) in the lecturer view, below the "Help and Support" called "Feedback/Suggestions/Bugs" (or something similar)
(ii) in the student view, in the "options" three dots where students change their nicknames (not shown below - server doesn't have latest version?)

![image](https://cloud.githubusercontent.com/assets/4758245/12966627/230725ee-d0b4-11e5-9380-9a351f4ce0c2.png)

![image](https://cloud.githubusercontent.com/assets/4758245/12966811/5351be84-d0b5-11e5-8a6c-d3cf42afd37d.png)

**Comment by nathansherburn** [comment]
Link is up for the lecturer view.

Need the latest student view with the three dots to add link there.

**Comment by aj1331** [comment]
The latest student view is up but there's no three dots menu link (so far there's been no need for one). Feel free to add it.

Also the form permissions need too be changed:
![image](https://cloud.githubusercontent.com/assets/1275580/13159739/9a50b28a-d6e7-11e5-8e3c-a57565697851.png)

**Comment by thanatos6666** [comment]
I think this only happens for the role account. If it's a valid staff/student account, they don't see this message.
