### ISSUE TITLE
Monash College lecturers marked as students

### ISSUE THREAD

**Issue by nathansherburn** [SLC3/MARS#96]
Staff at Monash College are getting marked as students - may be because their emails end in ...@monashcollege.edu.au

Also we need to start using the private repo for Monash config :p

**Comment by aj1331** [comment]
It's not based on email address (nothing should be based on email address!), it's based on their group in LDAP:

```
'group': (ldapUser.monashOUCategory === 'Staff') 
  ? 'poller' 
  : 'responder'
```

Monash College users must be in a different group. Easy fix once we know what it is.

**Comment by nathansherburn** [comment]
Fixed with new SAML config
