### ISSUE TITLE
Export of data should include additional identifier fields 

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#97]
When exporting data, it has been requested to add in the pollers' student numbers in addition to their usernames.

This is a quality of life issue as some lecturers want to upload weekly participation marks to Moodle, which uses the student number as the identifier.

Does the MDS record give access to this?

**Comment by thanatos6666** [comment]
Seems more lecturers are asking me about this.

Can we please append "@student.monash.edu" at the end of the usernames on the export. This makes importing into Moodle vastly easier.

Also, in the "Marking" export mode:
- the second last column should be the sum of total questions answered for the user, while 
- the last column should be the sum of total questions correct.

If someone can do this sooner, rather than later, this would be good.

**Comment by thanatos6666** [comment]
Nathan, can you please test this resolution with some live data and if it's all good, add to next release?

**Comment by nathansherburn** [comment]
Closed https://github.com/SLC3/MARS/commit/0e25c42b0c5bef2de279b35718f695a64618c264
