### ISSUE TITLE
"My Feeds" view in audience mode is broken on small screens

### ISSUE THREAD

**Issue by nathansherburn** [SLC3/MARS#99]

**Comment by akdor1154** [comment]
This looks OK to me now on mobile FF and chrome (the dialog appears as a full screen overlay), you've updated dependencies since this was filed so is it possible that a new Angular Material has fixed the issues you were seeing?

**Comment by nathansherburn** [comment]
Thanks - I fixed this a while ago but forgot to close the issue.

https://github.com/SLC3/MARS/commit/24178bf99d6e4791b47ca6847f6b975054aad3ba
